Shader "VisAssets/IsosurfaceDoubleSided"
{
    Properties
    {
        _MainColor ("Base Color", Color) = (1, 1, 1, 1)
        _Glossiness ("Smoothness", Range(0,1)) = 0.5
        _Metallic ("Metallic", Range(0,1)) = 0.0
    }
    SubShader
    {
        // Set as an opaque object to ensure depth buffer writing
        Tags { "RenderType"="Opaque" "Queue"="Geometry" }
        LOD 200

        // Eliminate polygon front/back distinction (Double-sided rendering)
        Cull Off

        CGPROGRAM
        // 'addshadow' forces Unity to generate a perfect shadow (depth) pass inheriting the Cull Off setting.
        #pragma surface surf Standard fullforwardshadows addshadow
        #pragma target 3.0

        struct Input
        {
            // Receives the vertex color generated by the Isosurface module
            float4 color : COLOR;
        };

        half _Glossiness;
        half _Metallic;
        fixed4 _MainColor;

        void surf (Input IN, inout SurfaceOutputStandard o)
        {
            // Multiply vertex color with base color for texturing
            fixed4 c = IN.color * _MainColor;

            o.Albedo = c.rgb;
            o.Metallic = _Metallic;
            o.Smoothness = _Glossiness;
            o.Alpha = 1.0;
        }
        ENDCG
    }
    FallBack "VertexLit"
}