Shader "VisAssets/VertexColorLit"
{
	Properties
	{
		_MainColor ("Base Color", Color) = (1, 1, 1, 1)
		_Glossiness ("Smoothness", Range(0,1)) = 0.5
		_Metallic ("Metallic", Range(0,1)) = 0.0
	}

	SubShader
	{
		Tags
		{
			"RenderType"="Opaque"
			"Queue"="Geometry"
		}
		LOD 200

		// Render both front and back faces in a single pass
		Cull Off

		CGPROGRAM

		// Specify custom lighting model 'SciVis' and vertex shader 'vert'
		#pragma surface surf SciVis fullforwardshadows addshadow vertex:vert
		#pragma target 3.0
		#include "UnityPBSLighting.cginc"

		struct Input
		{
			float4 color : COLOR;
		};

		half   _Glossiness;
		half   _Metallic;
		fixed4 _MainColor;

		// ==========================================
		// 1. Vertex Shader: Prevent Shadow Acne
		// ==========================================
		// Safely normalize normals generated by the Compute Shader.
		// Unnormalized normals can cause severe self-shadowing artifacts in Unity.
		void vert (inout appdata_full v)
		{
			float len = length(v.normal);

			if (len > 0.0001)
			{
				v.normal /= len;
			}
		}

		// ==========================================
		// 2. Custom Lighting Function: Double-sided PBR
		// ==========================================
		// Modifying normals inside the 'surf' function without pre-calculated
		// tangents causes severe surface distortion. Therefore, we check and flip
		// the normal in world space right before the Standard PBR calculation.
		inline half4 LightingSciVis(SurfaceOutputStandard s, half3 viewDir, UnityGI gi)
		{
			// If the face is pointing away from the camera (back face), invert the normal
			if (dot(s.Normal, viewDir) < 0)
			{
				s.Normal = -s.Normal;
			}

			return LightingStandard(s, viewDir, gi);
		}

		inline void LightingSciVis_GI(SurfaceOutputStandard s, UnityGIInput data, inout UnityGI gi)
		{
			LightingStandard_GI(s, data, gi);
		}

		// ==========================================
		// 3. Surface Function
		// ==========================================
		// Do NOT modify o.Normal here to avoid Tangent Space generation bugs.
		// Purely pass the vertex colors and material properties.
		void surf (Input IN, inout SurfaceOutputStandard o)
		{
			fixed4 c = IN.color * _MainColor;

			o.Albedo = c.rgb;
			o.Metallic = _Metallic;
			o.Smoothness = _Glossiness;
			o.Alpha = 1.0;
		}

		ENDCG
	}

	FallBack "VertexLit"
}